<?php
$meigee_indigo_bgslider = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('meigee_indigo_bgslider');
$slider = $meigee_indigo_bgslider;
$mediaUrl = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('mediaurl');
if ($slider['slideroptions']['enabled']) {
    $html = "";
    $i = 0;
    foreach ($slider['slides'] as $slide) {
        if ($i > 0) {
            $html .= ', ';
        }
        $html .= '"' . $mediaUrl . $slide . '"';
        $i++;
    }
?>
<script>
        jQuery(window).load(function() {
            jQuery.backstretch([<?php echo $html;?>], {duration: <?php echo $slider['slideroptions']['duration']; ?>, fade: <?php echo $slider['slideroptions']['fade']; ?>});
        });
</script>
<?php 
}