<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
$meigee_indigo_general = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('meigee_indigo_general');
$footer_status = $meigee_indigo_general['footer']['footer_status'];
$footer_static = $meigee_indigo_general['footer']['footer_static'];
?>
<footer id="footer"<?php if($footer_status == 0){echo ' class="original"';}?>>
	<div class="container_12">
		<div class="grid_12">
			<?php if($footer_status == 1): ?>
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer_static)->toHtml() ?>
			<?php else: ?>
				<?php echo $this->getChildHtml('store_switcher') ?>
				<address><?php echo $this->getCopyright() ?></address>
				<div class="clear"></div>
			<?php endif; ?>
		</div>
		<div class="clear"></div>
	</div>
</footer>