<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
    $_product = $this->getProduct();
    $helpImg = $this->helper('ThemeOptionsIndigo/images');
	$meigee_indigo_productpage = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('meigee_indigo_productpage');

    if ($_product->getIndigoRelatedpos() == 0) {
        $rel_pos = $meigee_indigo_productpage['general']['relatedposition'];
    }
    else {
        switch ($_product->getIndigoRelatedpos()) {
            case 2:
                $rel_pos = 'sidebar';
                break;
            case 3:
                $rel_pos = 'bottom';
                break;
            default:
                $rel_pos = 'sidebar';
                break;
        }
    }


    if ($rel_pos == 'sidebar') {

    $productpage_additional = $meigee_indigo_productpage['additional'];
    if($this->getItems()->getSize()):
    $productpage_collateral_related = $meigee_indigo_productpage['general']['collateral_related'];
    if ($_product->getIndigoPrrelatedcontent()):
        echo $_product->getIndigoPrrelatedcontent();
    elseif ($productpage_additional['product_related_content']):
            $product_related_blocks = explode(",", $productpage_additional['product_related_content']);
            foreach ($product_related_blocks as $product_related_block) {
                echo '<div class="product-custom-related">' . $this->getLayout()->createBlock('cms/block')->setBlockId(trim($product_related_block))->toHtml() . '</div>';
            };
    else:
?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->__('Related Products') ?></span></strong>
    </div>
    <div class="block-content">
		<p class="block-subtitle"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a></p>
        <div <?php if ($productpage_collateral_related == 'related_slider' && count($this->getItems())>5): ?>id="block-related-slider"<?php else:?> class="no-slider" <?php endif; ?>>
            <ul class="carousel-ul">
            <?php $i=0; foreach($this->getItems() as $_item): ?>
                <li class="item">
                    <div class="product">
                        <div class="grid-indent">
                            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img <?php echo $helpImg->getImgSources($_item, 'thumbnail', 240, null); ?> alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
							<p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
                            <div class="product-details">
                                <?php echo $this->getPriceHtml($_item, true, '-related') ?>
								<?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php $i++; endforeach ?>
            </ul>
        </div>
    </div>
    <?php if ($productpage_collateral_related == 'related_slider' && count($this->getItems())>5): ?>
	<div class = 'next'><i class="fa fa-angle-right"></i></div>
    <div class = 'prev unselectable'><i class="fa fa-angle-left"></i></div>
	<?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('deselect all') ?>";
			txt.addClassName('selected');
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
			txt.innerHTML="<?php echo $this->__('select all') ?>";
			txt.removeClassName('selected');
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }
    //]]>
	
    </script>
</div>
<?php 
    endif;
endif;
}