<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    
    $meigee_indigo_general = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('meigee_indigo_general');
	$fancybox = $meigee_indigo_general['fancybox'];
    $helpImg = $this->helper('ThemeOptionsIndigo/images');
	$labelsoptions = $meigee_indigo_general['productlabels'];
	$productOnlyXleft = $meigee_indigo_general['productlabels']['labelonlyxleft'];
	$labelsType = $meigee_indigo_general['productlabels']['labelview'];
	$labelsPosition = $meigee_indigo_general['productlabels']['labelsposition'];
?>
<?php // Grid Mode ?>
<div class="home-container grid">
    <div class="meigee-widget">
        <ul class="products-grid<?php echo ' '.$labelsType.' '.$labelsPosition; ?> widget-grid">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="grid_3 item<?php if($labelsoptions['labelsorder'] == 'sale_new'):?> labels-sale-new<?php endif; ?>">
                <div class="product-container">
					<div class="product-img-box">
						<?php echo MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new'); ?>
						<?php if (!MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new')) : ?>
							<div class="no-label-new">
						<?php endif; ?>
						<?php if($productOnlyXleft and MAGE::helper('ThemeOptionsIndigo')->getProductOnlyXleft($_product)): ?>
							<?php echo MAGE::helper('ThemeOptionsIndigo')->getProductOnlyXleft($_product); ?>
						<?php else: ?>
							<?php echo MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'sale'); ?>
						<?php endif; ?>
						<?php if (!MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new')) : ?>
							</div>
						<?php endif; ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
							<?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 420, null); ?><img <?php echo $helpImg->getImgSources($_product, 'small_image', 420, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							<span class="image-box"></span>
							<?php if(MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new') || MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'sale') || MAGE::helper('ThemeOptionsIndigo')->getProductOnlyXleft($_product)): ?>
							<span class="label-shadow"></span>
							<?php endif; ?>
						</a>
						<?php  // Fancybox
						if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
								<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('fancybox'); ?></a>
							<?php endif;
						// End Fancybox ?>
						<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
							<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('quickview'); ?></span></span></button>
							<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
						<?php } ?>
					</div>
					<div class="actions">
						<div class="indent">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						</div>
					</div>
					<?php echo $this->getPriceHtml($_product, true) ?>
				</div>
            </li>
        <?php if ($i+1 == $_collectionSize ) break; $i++; endforeach ?>        
        </ul> 
    </div>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   afterLoad: function(){
						setTimeout(function(){
							var frameBodyHeight = jQuery('.fancybox-iframe').contents().find('body').height();
							if(jQuery(window).height() > frameBodyHeight+30){
								jQuery('.fancybox-inner').css('height', frameBodyHeight);
							}
						}, 1000);
					}
				}
			);
			
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				/* if(jQuery('.header .links')){
					jQuery('.header .links').replaceWith(data.toplink);
				} */
				jQuery.fancybox.close();
				jQuery('body').append('<div class="add-to-cart-success">' + data.message +' <br /><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('Go to Shopping Cart') ?></span></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
				setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);
				jQuery('.add-to-cart-success a.btn-remove').click(function(){
					jQuery(this).parent().slideUp(500);
					return false;
				});
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
	</script>
</div>