<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();

    
    $meigee_indigo_general = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('meigee_indigo_general');
	$fancybox = $meigee_indigo_general['fancybox'];
    $helpImg = $this->helper('ThemeOptionsIndigo/images');
	$labelsoptions = $meigee_indigo_general['productlabels'];
	$productOnlyXleft = $meigee_indigo_general['productlabels']['labelonlyxleft'];
	$labelsType = $meigee_indigo_general['productlabels']['labelview'];
	$labelsPosition = $meigee_indigo_general['productlabels']['labelsposition'];
?>
<?php // List Mode ?>
<ol class="products-list<?php echo ' '.$labelsType.' '.$labelsPosition; ?> meigee-widget" id="products-list">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php $_iterator=0; if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?><?php if($labelsoptions['labelsorder'] == 'sale_new'):?> labels-sale-new<?php endif; ?>">
            <?php // Product Image ?>
            <div class="grid_3 alpha">
                <div class="product-img-box">
					<?php echo MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new'); ?>
					<?php if (!MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new')) : ?>
						<div class="no-label-new">
					<?php endif; ?>
					<?php if($productOnlyXleft and MAGE::helper('ThemeOptionsIndigo')->getProductOnlyXleft($_product)): ?>
						<?php echo MAGE::helper('ThemeOptionsIndigo')->getProductOnlyXleft($_product); ?>
					<?php else: ?>
						<?php echo MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'sale'); ?>
					<?php endif; ?>
					<?php if (!MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new')) : ?>
						</div>
					<?php endif; ?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
						<?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 420, null); ?><img <?php echo $helpImg->getImgSources($_product, 'small_image', 420, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						<span class="image-box"></span>
						<?php if(MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'new') || MAGE::helper('ThemeOptionsIndigo')->getProductLabels($_product, 'sale') || MAGE::helper('ThemeOptionsIndigo')->getProductOnlyXleft($_product)): ?>
						<span class="label-shadow"></span>
						<?php endif; ?>
					</a>
                    <?php // Fancybox
                    if ($fancybox['fancybox_status'] && $fancybox['fancybox_home'] == 1): ?>
						<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('fancybox'); ?></a>
                    <?php endif; // End Fancybox ?>
					<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
						<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('quickview'); ?></span></span></button>
						<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
					<?php } ?>
                </div>
            </div>
            <?php // Product description ?>
            <div class="<?php if($this->getLayout()->getBlock('root')->getTemplate() == 'page/1column.phtml'){echo 'grid_9';}else{echo 'grid_6';} ?> omega">
				<div class="product-shop">
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
					<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product) ?>
					<?php endif; ?>
					<div class="clear"></div>
					<?php echo $this->getPriceHtml($_product, true) ?>
					
					<?php if(!$_product->isSaleable()): ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif; ?>
					
					<div class="desc std">
						<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
					</div>
					
					<?php if($_product->isSaleable()): ?>
						<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
							<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped() || $_product->isConfigurable()) ): ?>
								<div class="button-holder">
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<span id='ajax_loader<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt='' /></span>
								</div>
							<?php else: ?>
								<div class="button-holder">
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
								</div>
							<?php endif; ?>
						<?php }else{ ?>
							 <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php } ?>
					<?php endif; ?>
					<div class="clear"></div>
					<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
					 <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('wishlist'); ?><?php echo $this->__('Add to Wishlist') ?><span id='ajax_wishlist_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt='' /></span></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('compare'); ?><?php echo $this->__('Add to Compare') ?><span id='ajax_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt='' /></span></a></li>
                        <?php endif; ?>
                    </ul>
					<?php }else{?>
					<ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('wishlist'); ?><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('compare'); ?><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
						  </ul>
					<?php } ?>
					<p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo MAGE::helper('ThemeOptionsIndigo')->getIcon('emailfiend'); ?><?php echo $this->__('Email to a Friend') ?></a></p>
				</div>
            </div>
        </li>
    <?php if (++$i == $_collectionSize ) break; endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   onComplete: function(){
					jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
						jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
						jQuery.fancybox.resize();
					 });

				   }
				}
			);
			
			/* Quick Shop buttons */
			function quickViewButton(){
				setTimeout(function(){
					jQuery('button.btn-quick-view').each(function(){
						var buttonWidth = jQuery(this).children('span').outerWidth();
						var imageWidth = jQuery(this).parent().width();
						jQuery(this).css('margin-left', (imageWidth-buttonWidth)/2);
					});
				}, 500);
			}
			quickViewButton();
			jQuery(window).resize(function(){
				quickViewButton();
			});
			
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				/* if(jQuery('.header .links')){
					jQuery('.header .links').replaceWith(data.toplink);
				} */
				jQuery.fancybox.close();
				jQuery('body').append('<div class="add-to-cart-success">' + data.message +' <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><br /><span><?php echo $this->__('Go to Shopping Cart') ?></span></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
				setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);
				jQuery('.add-to-cart-success a.btn-remove').click(function(){
					jQuery(this).parent().slideUp(500);
					return false;
				});
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
	</script>