<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>

<div class="block block-subscribe">
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
		<div class="block-title">
			<strong><span><?php echo $this->__('Newsletter') ?></span></strong>
		</div>
		<div class="block-content">
			<label for="newsletter"><?php echo $this->__('Subscribe to the Indigo mailing list to receive updates on new arrivals, special offers and other discount information.') ?></label>
			<div class="input-box">
				<input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" value="<?php echo $this->__('Sign up for our newsletter') ?>" onblur="if (this.value=='') this.value = '<?php echo $this->__('Sign up for our newsletter') ?>'" onfocus="if (this.value=='<?php echo $this->__('Sign up for our newsletter') ?>') this.value = ''" />
				<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
				<div class="clear"></div>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
//<![CDATA[
	var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>