<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
 
$meigee_indigo_general = MAGE::helper('ThemeOptionsIndigo')->getThemeOptionsIndigo('meigee_indigo_general'); 
$layout = $meigee_indigo_general['layout']['sitelayout'];
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php if ($layout == 1): ?>
<div class="container_12 boxed">
<?php endif; ?>
<?php echo $this->getChildHtml('header') ?>
<div class="content-wrapper">
    <div class="container_12">
		<?php echo $this->getChildHtml('breadcrumbs') ?>
        <div class="main-container col2-right-layout">
            <div class="grid_9 col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <aside class="grid_3 sidebar sidebar-right">
				<div class="indent">
					<?php echo $this->getChildHtml('right') ?>
				</div>
            </aside>
            <div class="clear"></div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php if ($layout == 1): ?>
</div>
<?php endif; ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>