<script data-adroll="magento-adroll-pixel" type="text/javascript">
<?php if ($this->isConfigured()): ?>
    <?php
        foreach($this->getGlobalVars() as $name => $value) {
            echo "$name = " . json_encode($value) . ";\n";
        }
    ?>

    (function(w,d,e,o,a){
        w.__adroll_loaded=true;
        w.adroll=w.adroll||[];
        w.adroll.f=['setProperties','identify','track'];
        var roundtripUrl="https://s.adroll.com/j/" + adroll_adv_id + "/roundtrip.js";
        for(a=0;a<w.adroll.f.length;a++){
            w.adroll[w.adroll.f[a]]=w.adroll[w.adroll.f[a]]||(function(n){return function(){w.adroll.push([n,arguments])}})(w.adroll.f[a])};e=d.createElement('script');o=d.getElementsByTagName('script')[0];e.async=1;e.src=roundtripUrl;o.parentNode.insertBefore(e, o);})(window,document);

    <?php
        $customerEmail = $this->getCustomerEmail();
        if ($customerEmail) {
            $payload = json_encode(array('email' => md5($customerEmail)));
            echo "adroll.identify($payload);\n";
        }

        $properties = json_encode($this->getPixelProperties());
        echo "console.log('Adroll setProperties: ', $properties);\n";
        echo "adroll.setProperties($properties);\n";

        foreach($this->getEvents() as $event) {
            $name = $event['name'];
            $payload = $event['payload'];

            if ($payload) {
                $payload = json_encode($payload);
                echo "console.log('AdRoll track event: $name', $payload);\n";
                echo "adroll.track('$name', $payload);\n";
            } else {
                echo "console.log('AdRoll track event: $name');\n";
                echo "adroll.track('$name');\n";
            }
        }
    ?>
<?php endif; ?>
</script>
